### ISSUE TITLE
KeyError: 'gene'

### ISSUE THREAD

**Issue by BushraYusufkhan** [marcelauliano/MitoHiFi#81]
Hi,
I am using mitohifi to analyze nematode raw sequence data. Everthing is running smooth till the very end and then it get this keyerror.

Input:
 docker run -u $(id -u) -v $(pwd):$PWD ghcr.io/marcelauliano/mitohifi:master mitohifi.py -r /home/bkhan/Data/Diploscapter_oocerea/m54274Ue_220811_201236.hifi_reads.fastq.gz -f /home/bkhan/Data/Diploscapter_oocerea/LC213018.1.fasta -g /home/bkhan/Data/Diploscapter_oocerea//LC213018.1.gb -t 12 -o 5

Error message:

2024-03-06 14:07:04 [INFO] 8. Now we will choose the most representative contig

2024-03-06 14:07:06 [INFO] Representative contig is ptg000002l that belongs to Cluster 1. This contig will be our final mitogenome. See all contigs and clusters in cdhit.out.clstr
2024-03-06 14:07:06 [INFO] 9. Calculating final stats for final mitogenome and other potential contigs.
    Stats will be saved on contigs_stats.tsv file.
Traceback (most recent call last):
  File "/opt/MitoHiFi/src/mitohifi.py", line 567, in <module>
    main()
  File "/opt/MitoHiFi/src/mitohifi.py", line 426, in main
    related_mito_genes = get_genes_list(related_mito_annotation, "genbank")
  File "/opt/MitoHiFi/src/getGenesList.py", line 25, in get_genes_list
    genes.append(feat.qualifiers['gene'][0])
KeyError: 'gene'

How can I fix this, what could be the problem? 
I have already checked mitohif on the test data and it works fine.
Thank You.

**Comment by BushraYusufkhan** [comment]
This is an issue of the reference file, when I used a different reference file it worked. This is similar to the issue,
https://github.com/marcelauliano/MitoHiFi/issues/49 

But I will still request the team to look into this matter, what is the matter with some of the Genbank files, that it gives key errors and make changes to the code accordingly.

**Comment by marcelauliano** [comment]
Good you resolved the issue by changing the reference. This is the best way to go, as we don't have time at the moment to look into all corner cases concerning the annotation in gb format.
Best,
Marcela.

**Comment by abueg** [comment]
hi @marcelauliano !! sorry to comment on a closed issue, but I've actually encountered this one before as well, so I'm not sure if it's a corner case... it seems there are some NCBI annotations that do not have "gene" listed for the CDS features, but instead "product". switching line 25 to use "product" lets `getGenesList.py` run: 

<img width="1060" alt="image" src="https://github.com/marcelauliano/MitoHiFi/assets/48773001/f63f75d7-c572-49d0-815c-c28436fe8c29">

do you think making this edit would throw issues downstream, because the "product" name is lengthier than the "gene" name?
